"use client";

import { useState } from "react";
import Link from "next/link";
import { 
  FileCheck, 
  Download, 
  Search, 
  ArrowLeft,
  MoreVertical,
  CalendarDays,
  Trash2,
  Edit,
  X,
  FileText
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { DocumentSection } from "@/types/workspace";

// --- MOCK DATA ---
const INITIAL_REPORTS: DocumentSection[] = [
  { 
    id: "rep-001", 
    title: "Ventilation Analysis - Master Bedroom", 
    content: "The window-to-floor ratio is currently at 8%, violating Rule VII. Code requires 10%.\n\nRecommendation: Increase window width by 0.4m.", 
    status: 'approved', 
    lastUpdated: new Date('2024-05-12T14:30:00'),
    tags: ['Ventilation', 'Rule VII', 'Taguig Tower']
  },
  { 
    id: "rep-002", 
    title: "Parking Slot Dimensions Check", 
    content: "Parallel parking slots observed are 2.0m x 5.0m. Code requires 2.15m x 6.0m for standard slots.", 
    status: 'approved', 
    lastUpdated: new Date('2024-05-10T09:15:00'),
    tags: ['Parking', 'Rule VII', 'Makati Complex']
  },
  { 
    id: "rep-003", 
    title: "Setback Compliance - Front Yard", 
    content: "R-1 Zone requires 4.5m setback. Plan shows 2.0m.", 
    status: 'rejected', 
    lastUpdated: new Date('2024-05-08T11:20:00'),
    tags: ['Setbacks', 'Quezon City']
  },
];

export default function ReportsPage() {
  const [reports, setReports] = useState<DocumentSection[]>(INITIAL_REPORTS);
  const [editingReport, setEditingReport] = useState<DocumentSection | null>(null);
  const [isDeleteOpen, setIsDeleteOpen] = useState<string | null>(null);

  // --- ACTIONS ---

  const handleExportPDF = () => {
    // 1. Generate a clean HTML string for the "document"
    const reportContent = reports.map(r => `
        <div style="margin-bottom: 40px; border-bottom: 2px solid #eee; padding-bottom: 20px;">
            <h2 style="font-family: 'Helvetica Neue', sans-serif; margin-bottom: 5px; color: #333;">${r.title}</h2>
            <div style="font-size: 12px; color: #666; margin-bottom: 15px; font-family: monospace;">
                STATUS: ${r.status.toUpperCase()} | DATE: ${r.lastUpdated.toLocaleDateString()}
            </div>
            <div style="font-family: 'Georgia', serif; line-height: 1.6; color: #444; white-space: pre-wrap;">${r.content}</div>
        </div>
    `).join('');

    // 2. Open a new window and write the content
    const printWindow = window.open('', '_blank');
    if (printWindow) {
        printWindow.document.write(`
            <html>
                <head>
                    <title>Architectural Compliance Report</title>
                </head>
                <body style="padding: 60px; max-width: 800px; margin: 0 auto;">
                    <div style="text-align: center; margin-bottom: 60px; border-bottom: 4px solid #000; padding-bottom: 20px;">
                        <h1 style="font-family: 'Helvetica Neue', sans-serif; letter-spacing: -1px; margin: 0;">RULE VII ARCHITECT</h1>
                        <p style="font-family: monospace; color: #666; margin-top: 5px;">AI-GENERATED COMPLIANCE REPORT</p>
                    </div>
                    ${reportContent}
                    <div style="margin-top: 50px; text-align: center; font-size: 10px; color: #999;">
                        Generated by AI Architect. Verify with National Building Code (PD 1096).
                    </div>
                    <script>
                        // Automatically trigger print when loaded
                        window.onload = function() { window.print(); }
                    </script>
                </body>
            </html>
        `);
        printWindow.document.close();
    }
  };

  const handleDelete = () => {
    if (isDeleteOpen) {
        setReports(prev => prev.filter(r => r.id !== isDeleteOpen));
        setIsDeleteOpen(null);
    }
  };

  const handleSaveEdit = (e: React.FormEvent) => {
    e.preventDefault();
    if (editingReport) {
        setReports(prev => prev.map(r => r.id === editingReport.id ? editingReport : r));
        setEditingReport(null);
    }
  };

  return (
    <div className="flex-1 flex flex-col h-screen bg-neutral-50/40 dark:bg-neutral-950 overflow-hidden relative">
      
      {/* 1. HEADER */}
      <div className="px-8 py-6 border-b border-border/40 flex items-center justify-between bg-background/50 backdrop-blur-sm sticky top-0 z-10">
        <div className="flex items-center gap-4">
             {/* BACK BUTTON */}
             <Link href="/dashboard">
                <Button variant="ghost" size="icon" className="rounded-full hover:bg-muted">
                    <ArrowLeft className="w-5 h-5 text-muted-foreground" />
                </Button>
            </Link>
            <div>
                <h1 className="text-2xl font-heading font-semibold text-foreground">Saved Reports</h1>
                <p className="text-sm text-muted-foreground mt-0.5">High-value insights saved from your chats.</p>
            </div>
        </div>
        <div className="flex gap-2">
            <Button variant="outline" className="gap-2 shadow-sm" onClick={handleExportPDF}>
                <Download className="w-4 h-4" />
                Export as PDF
            </Button>
        </div>
      </div>

      {/* 2. CONTENT */}
      <div className="flex-1 overflow-y-auto p-8">
        <div className="max-w-5xl mx-auto space-y-6">
          
          {/* SEARCH */}
          <div className="relative max-w-md">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                <Input 
                placeholder="Filter by keyword..." 
                className="pl-9 bg-background/50 border-border/50 rounded-xl focus:bg-background transition-all"
                />
          </div>

          {/* LIST */}
          <div className="space-y-3 pb-20">
             {reports.length === 0 ? (
                <div className="text-center py-20 opacity-50 border-2 border-dashed border-border rounded-xl">
                    <FileCheck className="w-12 h-12 mx-auto mb-4 text-muted-foreground" />
                    <h3 className="text-lg font-medium">No saved reports yet</h3>
                    <p className="text-sm">Approve drafts in the chat to see them here.</p>
                </div>
             ) : (
                 reports.map((report) => (
                    <ReportItem 
                        key={report.id} 
                        report={report} 
                        onEdit={() => setEditingReport(report)}
                        onDelete={() => setIsDeleteOpen(report.id)}
                    />
                 ))
             )}
          </div>

        </div>
      </div>

      {/* --- MODALS --- */}

      {/* 3. EDIT MODAL */}
      {editingReport && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm animate-in fade-in duration-200">
            <div className="w-full max-w-lg bg-background border border-border rounded-xl shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200">
                <div className="px-6 py-4 border-b border-border flex justify-between items-center bg-muted/30">
                    <h3 className="font-semibold text-lg">Edit Report Details</h3>
                    <Button variant="ghost" size="icon" onClick={() => setEditingReport(null)} className="h-8 w-8 rounded-full">
                        <X className="w-4 h-4" />
                    </Button>
                </div>
                <form onSubmit={handleSaveEdit} className="p-6 space-y-4">
                    <div className="space-y-2">
                        <label className="text-sm font-medium text-muted-foreground">Title</label>
                        <Input 
                            value={editingReport.title} 
                            onChange={(e) => setEditingReport({...editingReport, title: e.target.value})}
                        />
                    </div>
                    {/* Just a visual preview of content for now */}
                    <div className="space-y-2">
                         <label className="text-sm font-medium text-muted-foreground">Content Preview (Read Only)</label>
                         <div className="p-3 bg-muted/50 rounded-md text-xs text-muted-foreground font-mono line-clamp-4">
                            {editingReport.content}
                         </div>
                    </div>
                    <div className="pt-2 flex gap-3 justify-end">
                        <Button type="button" variant="ghost" onClick={() => setEditingReport(null)}>Cancel</Button>
                        <Button type="submit">Save Changes</Button>
                    </div>
                </form>
            </div>
        </div>
      )}

      {/* 4. DELETE CONFIRMATION MODAL */}
      {isDeleteOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-in fade-in duration-200">
            <div className="w-full max-w-sm bg-background border border-border rounded-xl shadow-2xl p-6 animate-in zoom-in-95 duration-200">
                <div className="flex flex-col items-center text-center gap-4">
                    <div className="w-12 h-12 rounded-full bg-red-100 dark:bg-red-900/30 flex items-center justify-center text-red-600">
                        <Trash2 className="w-6 h-6" />
                    </div>
                    <div>
                        <h3 className="text-lg font-semibold">Delete Report?</h3>
                        <p className="text-sm text-muted-foreground mt-1">
                            This action cannot be undone. This report will be removed from your saved list.
                        </p>
                    </div>
                    <div className="flex gap-3 w-full mt-2">
                        <Button variant="outline" className="flex-1" onClick={() => setIsDeleteOpen(null)}>Cancel</Button>
                        <Button variant="destructive" className="flex-1" onClick={handleDelete}>Delete</Button>
                    </div>
                </div>
            </div>
        </div>
      )}

    </div>
  );
}

// --- SUB-COMPONENT ---

function ReportItem({ report, onEdit, onDelete }: { report: DocumentSection, onEdit: () => void, onDelete: () => void }) {
    const [isMenuOpen, setIsMenuOpen] = useState(false);

    return (
        <div className="group flex flex-col md:flex-row md:items-center gap-4 p-5 bg-card/50 hover:bg-card border border-border/50 hover:border-primary/30 rounded-xl transition-all hover:shadow-md">
            
            {/* ICON */}
            <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                <FileText className="w-5 h-5 text-primary" />
            </div>

            {/* TEXT */}
            <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1">
                    <h4 className="font-semibold text-foreground truncate">{report.title}</h4>
                    {report.status === 'rejected' && (
                        <Badge variant="destructive" className="text-[10px] h-5 px-1.5">Discarded</Badge>
                    )}
                </div>
                <div className="flex items-center gap-3 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1">
                        <CalendarDays className="w-3 h-3" />
                        {report.lastUpdated.toLocaleDateString()}
                    </span>
                    <span className="w-1 h-1 rounded-full bg-border" />
                    <div className="flex gap-1">
                        {report.tags?.map(tag => (
                            <span key={tag} className="bg-muted px-1.5 py-0.5 rounded-sm text-[10px] uppercase tracking-wider">
                                {tag}
                            </span>
                        ))}
                    </div>
                </div>
            </div>

            {/* ACTIONS */}
            <div className="flex items-center gap-2">
                {/* Visual-only View Content Button */}
                <Button size="sm" variant="ghost" className="gap-2 text-xs opacity-0 group-hover:opacity-100 transition-opacity">
                    View Content
                </Button>

                {/* Dropdown Menu */}
                <div className="relative">
                    <Button 
                        size="icon" 
                        variant="ghost" 
                        className="h-8 w-8 text-muted-foreground hover:text-foreground"
                        onClick={() => setIsMenuOpen(!isMenuOpen)}
                    >
                        <MoreVertical className="w-4 h-4" />
                    </Button>

                    {isMenuOpen && (
                        <>
                            <div className="fixed inset-0 z-10" onClick={() => setIsMenuOpen(false)} />
                            <div className="absolute right-0 mt-2 w-32 bg-popover border border-border rounded-lg shadow-lg z-20 py-1 animate-in fade-in zoom-in-95 duration-100">
                                <button 
                                    className="w-full text-left px-3 py-2 text-xs hover:bg-muted flex items-center gap-2 text-foreground"
                                    onClick={() => { onEdit(); setIsMenuOpen(false); }}
                                >
                                    <Edit className="w-3 h-3" /> Edit Details
                                </button>
                                <button 
                                    className="w-full text-left px-3 py-2 text-xs hover:bg-red-50 text-red-600 dark:hover:bg-red-900/20 flex items-center gap-2"
                                    onClick={() => { onDelete(); setIsMenuOpen(false); }}
                                >
                                    <Trash2 className="w-3 h-3" /> Delete
                                </button>
                            </div>
                        </>
                    )}
                </div>
            </div>
        </div>
    )
}