"use client";

import { useState, useEffect } from "react";
import { FileText, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { DocumentSection } from "@/types/workspace";
import { motion, AnimatePresence } from "framer-motion";

interface DocumentPanelProps {
  sections: DocumentSection[];
}

export default function DocumentPanel({ sections }: DocumentPanelProps) {
  const [dateStr, setDateStr] = useState("");

  useEffect(() => {
    setDateStr(new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }));
  }, []);

  const handleExport = () => {
    // Filter only approved sections (Double check)
    const approvedSections = sections.filter(s => s.status === 'approved');

    if (approvedSections.length === 0) {
      alert("No approved sections to export yet.");
      return;
    }

    console.log("Generating PDF for:", approvedSections);
    // TODO: Implement 'jspdf' or 'react-pdf' here later
    alert(`Exporting ${approvedSections.length} sections to PDF... (Feature coming next)`);
  };

  return (
    <div className="h-full flex flex-col bg-background border-l border-border">
      {/* Header */}
      <div className="h-14 px-4 border-b border-border flex items-center justify-between bg-card/50 backdrop-blur-sm">
        <div className="flex items-center gap-2">
          <div className="p-1.5 bg-primary/10 rounded-md">
            <FileText className="w-4 h-4 text-primary" />
          </div>
          <div>
            <h3 className="text-sm font-semibold leading-none">Specification</h3>
            <p className="text-[10px] text-muted-foreground mt-0.5">Live Draft • {sections.length} sections</p>
          </div>
        </div>

        {/* Only Download Button Remains */}
        <div className="flex items-center gap-1">
          <Button variant="ghost" size="icon" className="h-8 w-8" onClick={handleExport} title="Download PDF">
            <Download className="w-4 h-4" />
          </Button>
        </div>
      </div>

      {/* Content Area */}
      <ScrollArea className="flex-1 p-8">
        <div className="max-w-2xl mx-auto space-y-8 pb-20">

          {/* Document Title */}
          <div className="text-center space-y-2 mb-12 border-b border-border/50 pb-8">
            <h1 className="text-3xl font-heading font-bold tracking-tight">Architectural Compliance Report</h1>
            <p className="text-muted-foreground">Generated by Rule VII AI Architect</p>
            <div className="text-xs text-muted-foreground/50 font-mono mt-4">
              {dateStr}
            </div>
          </div>

          {/* Dynamic Sections */}
          <div className="space-y-6">
            <AnimatePresence mode="popLayout">
              {sections.length === 0 ? (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="text-center py-20 border-2 border-dashed border-border/50 rounded-xl bg-muted/20"
                >
                  <p className="text-muted-foreground font-medium">No sections approved yet.</p>
                  <p className="text-xs text-muted-foreground/60 mt-2 max-w-xs mx-auto">
                    Approve drafts in the chat to add them to this formal report.
                  </p>
                </motion.div>
              ) : (
                sections.map((section) => (
                  <motion.div
                    key={section.id}
                    layout
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    className="group relative"
                  >
                    <div className="absolute -left-4 top-0 bottom-0 w-0.5 bg-primary/20 opacity-0 group-hover:opacity-100 transition-opacity" />

                    <h2 className="text-lg font-bold text-foreground mb-3 flex items-center gap-2">
                      <span className="text-primary/40 text-sm font-mono">#{section.id.split('-')[1] || '01'}</span>
                      {section.title}
                    </h2>

                    <div className="prose prose-sm dark:prose-invert text-muted-foreground leading-relaxed whitespace-pre-wrap">
                      {section.content}
                    </div>

                    <div className="mt-4 flex items-center gap-2 text-[10px] text-muted-foreground/40 font-mono">
                      <span>STATUS: {section.status.toUpperCase()}</span>
                      <span>•</span>
                      <span>UPDATED: {section.lastUpdated.toLocaleTimeString()}</span>
                    </div>
                  </motion.div>
                ))
              )}
            </AnimatePresence>
          </div>
        </div>
      </ScrollArea>
    </div>
  );
}