"use client";

import { DocumentSection } from "@/types/workspace";
import { ScrollArea } from "@/components/ui/scroll-area";
import { FileCheck, Download } from "lucide-react";
import { Button } from "@/components/ui/button";

interface DocumentPanelProps {
    sections: DocumentSection[];
}

export default function DocumentPanel({ sections }: DocumentPanelProps) {
    if (sections.length === 0) {
        return (
            <div className="h-full flex flex-col items-center justify-center text-muted-foreground/40 p-8 text-center border-l border-border/50 bg-neutral-50/50 dark:bg-neutral-900/20">
                <FileCheck className="w-12 h-12 mb-4 opacity-20" />
                <h3 className="font-heading text-lg font-medium mb-1">Project Output</h3>
                <p className="text-sm">Approved analysis sections will appear here.</p>
            </div>
        );
    }

    return (
        <div className="h-full flex flex-col border-l border-border/50 bg-background">
            {/* Toolbar */}
            <div className="h-14 border-b border-border flex items-center justify-between px-6 bg-neutral-50/30 dark:bg-neutral-900/30">
                <span className="text-xs font-mono font-medium uppercase tracking-widest text-muted-foreground">
                    Live Document ({sections.length} Sections)
                </span>
                <Button variant="outline" size="sm" className="h-8 text-xs gap-2">
                    <Download className="w-3 h-3" />
                    Export PDF
                </Button>
            </div>

            {/* Document Content */}
            <ScrollArea className="flex-1 p-8 lg:p-12">
                <div className="max-w-2xl mx-auto space-y-8 pb-20">
                    <div className="mb-12 border-b border-foreground/10 pb-6">
                        <h1 className="text-3xl font-heading font-bold text-foreground">Architectural Compliance Report</h1>
                        <p className="text-sm text-muted-foreground mt-2">Generated by AI Architect • {new Date().toLocaleDateString()}</p>
                    </div>

                    {sections.map((section, index) => (
                        <div key={section.id} className="animate-in fade-in slide-in-from-bottom-4 duration-500">
                            <div className="flex items-baseline justify-between mb-3">
                                <h3 className="text-xl font-medium font-heading text-foreground/90">
                                    {index + 1}. {section.title}
                                </h3>
                                <span className="text-[10px] font-mono text-muted-foreground/50">
                                    REF-{section.id.substring(0,4).toUpperCase()}
                                </span>
                            </div>
                            <div className="prose prose-sm dark:prose-invert max-w-none text-muted-foreground/90 leading-relaxed">
                                {/* In a real app, use a Markdown renderer here */}
                                <p className="whitespace-pre-line">{section.content}</p>
                            </div>
                            <div className="my-8 border-b border-border/40" />
                        </div>
                    ))}
                </div>
            </ScrollArea>
        </div>
    );
}