"use client";

import { useState, useEffect, forwardRef } from "react";
import { FileText, Download, MoreHorizontal, Pencil, RefreshCw, Trash2, Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { DocumentSection } from "@/types/workspace";
import { motion, AnimatePresence } from "framer-motion";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { formatCitations } from "@/components/chat/citation-utils";
import { Scale } from "lucide-react";

interface DocumentPanelProps {
  sections: DocumentSection[];
  onDelete?: (id: string) => void;
  onEdit?: (section: DocumentSection) => void;
  onRevise?: (section: DocumentSection) => void;
  revisingSection?: DocumentSection | null;
  onLawClick?: (citation: string) => void;
}

export default function DocumentPanel({ sections, onDelete, onEdit, onRevise, revisingSection, onLawClick }: DocumentPanelProps) {
  const [dateStr, setDateStr] = useState("");

  useEffect(() => {
    setDateStr(new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }));
  }, []);

  const handleExport = async () => {
    const approvedSections = sections.filter(s => s.status === 'approved');

    if (approvedSections.length === 0) {
      alert("No approved sections to export yet.");
      return;
    }

    // Dynamic import of html2pdf for client-side only
    const html2pdf = (await import('html2pdf.js')).default;

    // Generate HTML content with proper styling
    const htmlContent = `
      <div style="font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif; color: #1a1a1a; padding: 40px;">
        <div style="text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #e5e5e5;">
          <h1 style="font-size: 24px; font-weight: 700; margin: 0 0 8px 0;">Architectural Compliance Report</h1>
          <p style="font-size: 12px; color: #666; margin: 0;">Generated by Rule VII AI Architect</p>
          <p style="font-size: 11px; color: #999; margin-top: 8px;">${dateStr}</p>
        </div>
        
        ${approvedSections.map((section, index) => `
          <div style="margin-bottom: 30px; ${index > 0 ? 'page-break-before: auto;' : ''}">
            <div style="display: flex; align-items: center; gap: 10px; margin-bottom: 12px;">
              <span style="background: #f5f5f5; padding: 4px 10px; border-radius: 4px; font-size: 12px; font-weight: 600; color: #666;">${index + 1}</span>
              <h2 style="font-size: 16px; font-weight: 600; margin: 0;">${section.title}</h2>
            </div>
            <div style="padding-left: 36px; font-size: 12px; line-height: 1.7; color: #333;">
              ${section.content
        .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
        .replace(/\*([^*]+)\*/g, '<em>$1</em>')
        .replace(/^- (.+)$/gm, '<li style="margin-left: 20px;">$1</li>')
        .replace(/^• (.+)$/gm, '<li style="margin-left: 20px;">$1</li>')
        .replace(/^(\d+)\. (.+)$/gm, '<li style="margin-left: 20px;">$2</li>')
        .replace(/^## (.+)$/gm, '<h3 style="font-size: 14px; font-weight: 600; margin: 16px 0 8px 0;">$1</h3>')
        .replace(/^### (.+)$/gm, '<h4 style="font-size: 13px; font-weight: 600; margin: 12px 0 6px 0;">$1</h4>')
        .replace(/☐/g, '☐')
        .replace(/✓/g, '✓')
        .replace(/⚠️/g, '⚠')
        .split('\n').join('<br/>')
      }
            </div>
          </div>
          ${index < approvedSections.length - 1 ? '<hr style="border: none; border-top: 1px solid #e5e5e5; margin: 20px 0;" />' : ''}
        `).join('')}
        
        <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e5e5; text-align: center;">
          <p style="font-size: 10px; color: #999;">This document was generated by Rule VII AI Architect. Please verify all references against official building codes.</p>
        </div>
      </div>
    `;

    // Create a temporary element
    const element = document.createElement('div');
    element.innerHTML = htmlContent;
    document.body.appendChild(element);

    // PDF options for professional output
    const opt = {
      margin: [15, 15, 15, 15],
      filename: `Compliance_Report_${new Date().toISOString().split('T')[0]}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      pagebreak: { mode: ['avoid-all', 'css', 'legacy'] }
    };

    try {
      await html2pdf().set(opt).from(element).save();
    } finally {
      document.body.removeChild(element);
    }
  };

  return (
    <div className="h-full flex flex-col bg-background">
      {/* Header */}
      <div className="h-14 px-4 border-b border-border flex items-center justify-between bg-card">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-muted rounded-lg border border-border">
            <FileText className="w-4 h-4 text-muted-foreground" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-foreground">Specification</h3>
            <p className="text-[10px] text-muted-foreground">{sections.length} sections</p>
          </div>
        </div>

        <Button
          variant="ghost"
          size="icon"
          className="h-8 w-8 text-muted-foreground hover:text-foreground"
          onClick={handleExport}
          title="Download PDF"
        >
          <Download className="w-4 h-4" />
        </Button>
      </div>

      {/* Content Area */}
      <ScrollArea className="flex-1 p-4">
        <div className="max-w-3xl mx-auto pb-12">

          {/* Document Title - Compact */}
          <div className="text-center mb-6 pb-4 border-b border-border">
            <h1 className="text-lg font-bold text-foreground tracking-tight">
              Architectural Compliance Report
            </h1>
            <p className="text-xs text-muted-foreground mt-0.5">Generated by Rule VII AI Architect</p>
            <div className="text-[10px] text-muted-foreground/60 font-mono mt-2">
              {dateStr}
            </div>
          </div>

          {/* Sections */}
          <div className="space-y-0">
            <AnimatePresence mode="popLayout">
              {sections.length === 0 ? (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="text-center py-16 border-2 border-dashed border-border rounded-xl bg-muted/20"
                >
                  <FileText className="w-10 h-10 text-muted-foreground/40 mx-auto mb-3" />
                  <p className="text-foreground font-medium">No sections approved yet</p>
                  <p className="text-xs text-muted-foreground mt-1 max-w-xs mx-auto">
                    Approve drafts in the chat to add them here
                  </p>
                </motion.div>
              ) : (
                sections.map((section, index) => (
                  <DocumentSectionItem
                    key={section.id}
                    section={section}
                    index={index + 1}
                    isLast={index === sections.length - 1}
                    onDelete={onDelete}
                    onRevise={onRevise}
                    onEdit={onEdit}
                    isRevising={revisingSection?.id === section.id}
                    onLawClick={onLawClick} // Pass down to item
                  />
                ))
              )}
            </AnimatePresence>
          </div>
        </div>
      </ScrollArea>
    </div>
  );
}

interface DocumentSectionItemProps {
  section: DocumentSection;
  index: number;
  isLast: boolean;
  onDelete?: (id: string) => void;
  onEdit?: (section: DocumentSection) => void;
  onRevise?: (section: DocumentSection) => void;
  isRevising?: boolean;
  onLawClick?: (citation: string) => void;
}

const DocumentSectionItem = forwardRef<HTMLDivElement, DocumentSectionItemProps>(
  function DocumentSectionItem({ section, index, isLast, onDelete, onEdit, onRevise, isRevising = false, onLawClick }, ref) {
    const [isMenuOpen, setIsMenuOpen] = useState(false);
    const [copied, setCopied] = useState(false);

    const handleCopy = async () => {
      await navigator.clipboard.writeText(`${section.title}\n\n${section.content}`);
      setCopied(true);
      setIsMenuOpen(false);
      setTimeout(() => setCopied(false), 2000);
    };

    return (
      <motion.div
        ref={ref}
        layout
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95 }}
        className="group"
      >
        {/* Section Card */}
        <div className="bg-card border border-border rounded-lg p-3 shadow-sm hover:shadow-md transition-shadow relative">
          {/* Loading Overlay */}
          {isRevising && (
            <div className="absolute inset-0 bg-background/80 backdrop-blur-sm rounded-lg flex items-center justify-center z-10">
              <div className="flex flex-col items-center gap-1.5">
                <div className="w-5 h-5 border-2 border-primary/30 border-t-primary rounded-full animate-spin"></div>
                <p className="text-xs text-muted-foreground">Revising...</p>
              </div>
            </div>
          )}

          {/* Header - Compact */}
          <div className="flex items-start justify-between mb-2">
            <div className="flex items-center gap-2">
              <span className="flex items-center justify-center w-5 h-5 rounded bg-muted text-[10px] font-bold text-muted-foreground">
                {index}
              </span>
              <h2 className="text-sm font-semibold text-foreground">
                {section.title}
              </h2>
            </div>

            {/* Actions Menu */}
            <div className="relative">
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7 opacity-0 group-hover:opacity-100 transition-opacity text-muted-foreground hover:text-foreground"
                onClick={() => setIsMenuOpen(!isMenuOpen)}
              >
                <MoreHorizontal className="w-4 h-4" />
              </Button>

              {isMenuOpen && (
                <>
                  <div className="fixed inset-0 z-40" onClick={() => setIsMenuOpen(false)} />
                  <div className="absolute right-0 mt-1 w-44 bg-popover border border-border rounded-lg shadow-lg z-50 py-1 animate-in fade-in zoom-in-95 duration-100">
                    <button
                      className="w-full text-left px-3 py-2 text-sm hover:bg-muted flex items-center gap-2 text-foreground"
                      onClick={handleCopy}
                    >
                      {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4 text-muted-foreground" />}
                      {copied ? "Copied!" : "Copy"}
                    </button>
                    <button
                      className="w-full text-left px-3 py-2 text-sm hover:bg-muted flex items-center gap-2 text-foreground"
                      onClick={() => { onRevise?.(section); setIsMenuOpen(false); }}
                    >
                      <RefreshCw className="w-4 h-4 text-blue-500" /> Revise with AI
                    </button>
                    <button
                      className="w-full text-left px-3 py-2 text-sm hover:bg-muted flex items-center gap-2 text-foreground"
                      onClick={() => { onEdit?.(section); setIsMenuOpen(false); }}
                    >
                      <Pencil className="w-4 h-4 text-amber-500" /> Edit Manually
                    </button>
                    <div className="h-px bg-border my-1" />
                    <button
                      className="w-full text-left px-3 py-2 text-sm hover:bg-red-50 dark:hover:bg-red-900/20 text-red-600 dark:text-red-400 flex items-center gap-2"
                      onClick={() => { onDelete?.(section.id); setIsMenuOpen(false); }}
                    >
                      <Trash2 className="w-4 h-4" /> Delete
                    </button>
                  </div>
                </>
              )}
            </div>
          </div>

          {/* Content - Compact with proper markdown */}
          <div className="pl-7">
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              urlTransform={(url) => url}
              components={{
                // Headers - Neutral sizes
                h1: ({ children }) => (
                  <h1 className="text-sm font-bold mb-2 mt-3 first:mt-0 text-foreground">{children}</h1>
                ),
                h2: ({ children }) => (
                  <h2 className="text-xs font-semibold mb-1.5 mt-2 first:mt-0 text-foreground">{children}</h2>
                ),
                h3: ({ children }) => (
                  <h3 className="text-xs font-semibold mb-1 mt-2 first:mt-0 text-foreground">{children}</h3>
                ),
                // Paragraphs - Compact
                p: ({ children }) => (
                  <p className="text-xs leading-relaxed mb-2 last:mb-0 text-muted-foreground">{children}</p>
                ),
                // Lists - Proper bullet points
                ul: ({ children }) => (
                  <ul className="list-disc list-outside ml-4 mb-2 space-y-0.5">{children}</ul>
                ),
                ol: ({ children }) => (
                  <ol className="list-decimal list-outside ml-4 mb-2 space-y-0.5">{children}</ol>
                ),
                li: ({ children }) => (
                  <li className="text-xs text-muted-foreground leading-relaxed pl-1">{children}</li>
                ),
                // Custom Link Renderer for Citations
                a: ({ node, href, children, ...props }) => {
                  const isLawLink = href?.startsWith('law:');

                  if (isLawLink) {
                    return (
                      <button
                        onClick={(e) => {
                          e.preventDefault();
                          if (onLawClick && href) {
                            onLawClick(decodeURIComponent(href.replace('law:', '')));
                          }
                        }}
                        className="inline-flex items-center mx-0.5 px-1.5 py-0 rounded bg-primary/10 hover:bg-primary/20 text-primary font-medium transition-colors cursor-pointer border border-primary/20 hover:border-primary/40 no-underline translate-y-[1px]"
                        title="View Law Details"
                      >
                        <Scale className="w-2.5 h-2.5 mr-1" />
                        {children}
                      </button>
                    );
                  }

                  return (
                    <a
                      href={href}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-primary underline hover:text-primary/80"
                      {...props}
                    >
                      {children}
                    </a>
                  );
                },
                // Bold & Italic
                strong: ({ children }) => (
                  <strong className="font-semibold text-foreground">{children}</strong>
                ),
                em: ({ children }) => (
                  <em className="italic">{children}</em>
                ),
                // Code - Compact
                code: ({ className, children }) => {
                  const isInline = !className;
                  return isInline ? (
                    <code className="px-1 py-0.5 bg-muted rounded text-[10px] font-mono text-primary">{children}</code>
                  ) : (
                    <code className="block bg-muted/50 rounded p-2 text-[10px] font-mono overflow-x-auto">{children}</code>
                  );
                },
                pre: ({ children }) => (
                  <pre className="bg-muted/50 rounded p-2 mb-2 overflow-x-auto text-[10px]">{children}</pre>
                ),
                // Tables - Compact
                table: ({ children }) => (
                  <div className="overflow-x-auto my-2 rounded border border-border">
                    <table className="w-full text-[10px]">{children}</table>
                  </div>
                ),
                thead: ({ children }) => (
                  <thead className="bg-muted/50 border-b border-border">{children}</thead>
                ),
                tbody: ({ children }) => (
                  <tbody className="divide-y divide-border">{children}</tbody>
                ),
                tr: ({ children }) => (
                  <tr className="hover:bg-muted/20 transition-colors">{children}</tr>
                ),
                th: ({ children }) => (
                  <th className="px-2 py-1 text-left text-[10px] font-semibold text-foreground">{children}</th>
                ),
                td: ({ children }) => (
                  <td className="px-2 py-1 text-[10px] text-muted-foreground">{children}</td>
                ),
                // Blockquote
                blockquote: ({ children }) => (
                  <blockquote className="border-l-2 border-primary/50 pl-2 py-0.5 my-2 italic text-muted-foreground text-xs">{children}</blockquote>
                ),
                // Horizontal rule
                hr: () => <hr className="border-border my-2" />,
              }}
            >
              {formatCitations(section.content)}
            </ReactMarkdown>
          </div>

          {/* Footer - Compact */}
          <div className="mt-2 pt-2 border-t border-border flex items-center gap-2 text-[9px] text-muted-foreground font-mono pl-7">
            <span className="px-1.5 py-0.5 bg-emerald-50 dark:bg-emerald-900/20 text-emerald-600 dark:text-emerald-400 rounded text-[9px]">
              {section.status.toUpperCase()}
            </span>
            <span>Updated {new Date(section.lastUpdated).toLocaleTimeString()}</span>
          </div>
        </div>

        {/* Separator between sections - Compact */}
        {!isLast && (
          <div className="flex items-center justify-center py-2">
            <div className="w-px h-4 bg-border"></div>
          </div>
        )}
      </motion.div>
    );
  }
);